[package]
name = "rearrange"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Alternative API for sorting by multiple properties"
repository = "https://github.com/panicbit/rearrange"
documentation = "https://docs.rs/rearrange"

[dependencies]
